blank_issues_enabled: true
contact_links:
  - name: Support
    url: https://discord.gg/**coming-shortly**
    about: Please ask and answer questions here
  - name: List a token
    url: https://doughnutswap.shop
    about: Any requests to add any token or pair to Doughnutswap should go here
